# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=256)),
                ('movie_url', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
