# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_site.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=64, unique=True)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('is_public', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=256)),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=64, unique=True)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('is_public', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(verbose_name='Grade')),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=384)),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('explanation', models.CharField(blank=True, max_length=384, null=True)),
                ('authority', models.SmallIntegerField(default=my_site.constants.QuestionAuthority(3), verbose_name='authority')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.SmallIntegerField(default=my_site.constants.Authority(1), verbose_name='Authority')),
                ('student_id', models.CharField(blank=True, max_length=24, null=True)),
                ('school', models.CharField(blank=True, max_length=24, null=True)),
                ('introduction', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=640, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted time')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_site.Submission')),
            ],
            bases=('my_site.submission',),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.MultipleChoice'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.MultipleChoice'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='my_site.MultipleChoice'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.MultipleChoice'),
        ),
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.ManyToManyField(blank=True, to='my_site.MultipleChoice'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.Exam'),
        ),
    ]
